###############################################################################
# MongoDB Docker image
#
# This Dockerfile builds an image with an instance of MongoDB
###############################################################################

FROM debian:jessie

MAINTAINER Jeff Chong <me@jeffchong.com>
