###############################################################################
# Nginx Web Server
#
# This is used for web development for simple websites or as a reverse proxy
# or load balancer
#
# This Dockerfile builds an Nginx server
###############################################################################

FROM debian:jessie

MAINTAINER Jeff Chong <me@jeffchong.com>
